.catalog:
    name: Kubernetes
    version: v1.2.0-alpha.8-rancher-1
    description: Manage a cluster of Linux containers as a single system to accelerate Dev and simplify Ops.
    questions:
        - variable: "api_server_port"
          label: "Kubernetes API port"
          type: "string"
          required: true
          default: "8090"
          description: This is the port that the Kubernetes API server should listen on.

api-server:
    health_check:
        request_line: GET /healthz HTTP/1.0
        port: 80
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2

etcd:
    health_check:
        request_line: GET /health HTTP/1.0
        port: 4001
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2

rancher-kubernetes-agent:
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 10240
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2

scheduler:
    health_check:
        request_line: GET /healthz HTTP/1.0
        port: 10251
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2

controller-manager:
    health_check:
        request_line: GET /healthz HTTP/1.0
        port: 10252
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
